global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sunotal-auth-service"
    static_configs:
      - targets: ["auth-service:5001"]

  - job_name: "sunotal-operations-service"
    static_configs:
      - targets: ["operations-service:5002"]

  - job_name: "sunotal-inventory-service"
    static_configs:
      - targets: ["inventory-service:5003"]

  - job_name: "sunotal-user-service"
    static_configs:
      - targets: ["user-service:5004"]

  - job_name: "sunotal-delivery-service"
    static_configs:
      - targets: ["delivery-service:5006"]
