apiVersion: v1
kind: ConfigMap
metadata:
  name: sunotal-config
  namespace: sunotal
data:
  NODE_ENV: "production"
  CLOUDFRONT_DOMAIN: "d3fif7cgb82sk5.cloudfront.net"
  FRONTEND_URL: "https://sunotal.automateuniverse.space"
  S3_BUCKET_NAME: "jcs-raju-sunotal-final"
  AWS_REGION: "us-east-1"
---
apiVersion: v1
kind: Secret
metadata:
  name: sunotal-secrets
  namespace: sunotal
type: Opaque
stringData:
  DATABASE_URL: "postgresql://sunotal:sunotalpass123@sunotal-postgres.cs1gq0a2wtpu.us-east-1.rds.amazonaws.com:5432/sunotal?sslmode=require&uselibpqcompat=true"
  SESSION_SECRET: "sunotal-super-secret-session-key"

