---
- name: "Teardown Infrastructure & Stop Microservices"
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Stop running Docker Compose containers
      command: docker compose down -v
      ignore_errors: true

    - name: Run Terraform Destroy if terraform directory exists
      command: terraform destroy -auto-approve
      args:
        chdir: "terraform"
      ignore_errors: true
