name: Infrastructure Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/infra.yml'
      - 'amplify.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/infra.yml'
      - 'amplify.yml'

env:
  AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}

jobs:
  validate_and_deploy:
    name: Provision AWS Amplify PaaS Infrastructure via Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.3"

      - name: Validate & Apply Terraform
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          cd terraform
          terraform init -upgrade
          if [ -n "$GH_TOKEN" ]; then
            terraform plan -var="github_access_token=${GH_TOKEN}"
            terraform apply -auto-approve -var="github_access_token=${GH_TOKEN}"
          else
            terraform plan
            terraform apply -auto-approve
          fi
